-- Generated from installed FFXI DAT ROM/332/48.DAT on 2026-06-18.
-- Adventuring Primer guide01 article detail text. DAT-backed; no fallback labels.
return {
    [1] = { title = 'Movement', description = 'Switching between autorun/walk character movement modes.', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [3] = { title = 'Targeting', description = 'Target cursor / Subtarget cursor / Self-targeting / Targeting NPCs / Targeting PCs / Targeting Monsters / Lockon', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [4] = { title = 'Action Commands', description = 'Chat / Chat window / Spells / Abilities / Items / Trade / Inspect / Inviting to a party', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [5] = { title = 'Chatting', description = 'Say / Shout / Tell / Party / Linkshell / Yell / Software keyboard / Auto-Translator', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [6] = { title = 'Camera', description = 'Moving the camera / Switching to first-person mode / Zoom in / Zoom out / Resetting the camera', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xC0 },
    [7] = { title = 'Log Windows', description = 'Show / Hide / Toggle / Split', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [8] = { title = 'Screenshots', description = 'Taking a screenshot / Checking screenshots', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [9] = { title = 'Logging Out', description = 'How to log out', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [10] = { title = 'Communication', description = 'Friends / Friend List / Blacklist / Adding to Blacklist / Editing Blacklist / Emotes / Executing Emotes', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xC8 },
    [11] = { title = 'Changing Equipment', description = 'Changing equipment / Selecting storage options / Equipment sets / Style Lock', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xE4 },
    [12] = { title = 'Forming a Party', description = 'Inviting / Accepting / Leaving / Kicking / Disbanding / Alliances / Focus', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [13] = { title = 'Combat', description = 'Fighting monsters / Checking a monster\'s strength / Aggressive monsters / Detecting / Linking / Calls for Help / Fleeing / Knocked Out', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xC0 },
    [14] = { title = 'Healing', description = 'HP and MP recovery', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xC0 },
    [15] = { title = 'Trading', description = 'Giving items to PCs and NPCs', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xC0 },
    [16] = { title = 'Auctions', description = 'Using the auction houses / Bidding / Putting up items / Succesful sales / Unsuccesful sales', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [17] = { title = 'Delivering Items', description = 'How to deliver items', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xE4 },
    [18] = { title = 'Bazaars', description = 'Selling from your bazaar / Buying from a player\'s bazaar / Bazaar comments', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xC0 },
    [19] = { title = 'Crystal Synthesis', description = 'Acquiring crystals / Synthesis guilds / Skill ranks / Synthesis procedure / Synthesis history / Setting favorites', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xE4 },
    [20] = { title = 'Synergy', description = 'Synergy and synergy furnaces / Fewell / Synergy Process / Evolith', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [21] = { title = 'Gathering', description = 'Gathering items / Mining / Logging / Harvesting / Gathering in Adoulin', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [22] = { title = 'Mog Houses', description = 'Residence district moogles / Nomad moogles / Mog safes / Furniture storage / Mog lockers / Second floor', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [23] = { title = 'Furnishings', description = 'Placing furnishings / Moghancements', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [24] = { title = 'Gardening', description = 'Placing flowerpots / Caring for plants / Harvesting', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [25] = { title = 'Changing Jobs', description = 'Changing job / Support jobs', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [26] = { title = 'Extra Jobs', description = 'Acquiring through quests / PLD DRK BST BRD RNG / SAM NIN DRA SUM / BLU COR PUP / DNC SCH / GEO RUN', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [27] = { title = 'Fishing', description = 'Fishing locations / Fishing rods and bait / Fighting a catch / Canceling reel-ins / Fisherman\'s Intuition / Fish ranking / Inside the Belly / Fisherman\'s Heart quest', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xC0 },
    [28] = { title = 'Transportation', description = 'Chocobos / Ferries / Airships / Manaclipper', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [29] = { title = 'Chocobo Digging', description = 'Rules of the game / Gysahl greens', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [30] = { title = 'Home Points', description = 'Home points / Teleporting between home points', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [31] = { title = 'Outpost Teleportation', description = 'Supply quests / Teleporting to outposts', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xF0 },
    [32] = { title = 'Survival Guides', description = 'Learn about survival guides', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [33] = { title = 'Waypoints', description = 'Waypoints / Kinetic units / Proto-waypoints', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [34] = { title = 'Linkshells', description = 'Linkshells / Linkshell vendors / Linkshell concierges', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [35] = { title = 'Text Commands', description = 'Text commands / List of commands', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [36] = { title = 'Macros', description = 'Macros / Registering macros / Editing macros / Using macros / Configuration examples', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xC0 },
    [37] = { title = 'Equipment Storage NPCs', description = 'Learn about armor depository NPCs', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xF0 },
    [38] = { title = 'Special Item Storage NPCs', description = 'Learn about item depository NPCs', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xFC },
    [39] = { title = 'Porter Moogles', description = 'Buying and using moogle storage slips', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [40] = { title = 'Inventory Expansion', description = 'Inventory expansion quests', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xE4 },
    [41] = { title = 'Mog Storage', description = 'Mog satchels / Mog sacks / Mog cases / Mog wardrobe', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [42] = { title = 'Limit Break Quests', description = 'Limit breaking / Maat\'s trials / Solo quests / Secrets of the masters', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xE4 },
    [43] = { title = 'Merit Points', description = 'Merit points / Limit points vs merit points', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [44] = { title = 'Job Points', description = 'Job points / Capacity points vs job points / Gifts / Superior items', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [45] = { title = 'Item Levels', description = 'Equipment item level / Average item level', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [46] = { title = 'Content Level', description = 'Learn about content levels', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [47] = { title = 'Level Sync', description = 'Learn about level syncing', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [48] = { title = 'Skills', description = 'Skills / Combat skills / Magic skills / Synthesis skills / Fishing skill / Synergy skill / Raising combat and synthesis skills', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xC0 },
    [49] = { title = 'Magic', description = 'Learning spells / White and black magic / Songs / Ninjutsu / Summoning spells / Blue magic / Indicolure geomancy / Geocolure geomancy', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xC0 },
    [50] = { title = 'Pet Commands', description = 'Pet commands / Beastmasters / Dragoons / Summoners / Puppetmasters', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [51] = { title = 'Learning Blue Magic', description = 'Learn about acquiring blue magic spells', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xE4 },
    [52] = { title = 'Phantom Roll', description = 'Phantom rolls / Dice results', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [53] = { title = 'Automatons', description = 'Automatons / Head and frame / Attachments / Elemental capacity and maneuvers / Overloading', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [54] = { title = 'Requesting to Join a Party', description = 'Requesting to join / Cancelling a request / Handling requests / Checking requests / Managing request history', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xFC },
    [55] = { title = 'Field Manuals', description = 'Fields of Valor / Grounds of Valor / Training regimes / Elite training / Field support', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [56] = { title = 'Treasure Caskets', description = 'Treasure caskets / Temporary items', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xE4 },
    [57] = { title = 'Coalition Assignments', description = 'Registering as a pioneer / Imprimaturs', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xF0 },
    [58] = { title = 'Records of Eminence', description = 'Setting the "First Step Forward" objective / Speaking to Records of Eminence guides', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xE4 },
    [59] = { title = 'Trust', description = 'Learn about Trust magic', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xC0 },
    [60] = { title = 'Unity Concord', description = 'Setting the "All for One" objective / Speaking to Unity guides', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [66] = { title = 'Adventuring Fellows', description = 'Learn about adventuring fellows', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xE4 },
    [71] = { title = 'Quests', description = 'Quests / Fame / Giving items / Using items / Quest battles / Quest guides', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xC0 },
    [72] = { title = 'Allegiance Missions', description = 'Nations of allegiance / Rank points', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xE4 },
    [73] = { title = 'Rise of the Zilart Missions', description = 'Rise of the Zilart missions', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xFC },
    [74] = { title = 'Chains of Promathia', description = 'Chains of Promathia missions', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xE4 },
    [75] = { title = 'Treasures of Aht Urhgan', description = 'Treasures of Aht Urhgan missions', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xF0 },
    [76] = { title = 'Wings of the Goddess', description = 'Wings of the Goddess missions', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xF0 },
    [77] = { title = 'A Crystalline Prophecy', description = 'A Crystalline Prophecy addon', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xF0 },
    [78] = { title = 'A Moogle Kupo d\'Etat', description = 'A Moogle Kupo d\'Etat addon', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xF0 },
    [79] = { title = 'A Shantotto Ascension', description = 'A Shantotto Ascension addon', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xF0 },
    [80] = { title = 'Vision of Abyssea', description = 'Vision of Abyssea addon', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xE4 },
    [81] = { title = 'Scars of Abyssea', description = 'Scars of Abyssea addon', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xE4 },
    [82] = { title = 'Heroes of Abyssea', description = 'Heroes of Abyssea addon', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xE4 },
    [83] = { title = 'Seekers of Adoulin', description = 'Seekers of Adoulin missions', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xE4 },
    [89] = { title = 'Skillchain List', description = 'A List of Skillchains', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [90] = { title = 'Skillchains', description = 'About Skillchains', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [97] = { title = 'Besieged', description = 'Learn about Besieged', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [104] = { title = 'Monstrosity', description = 'Learn about Monstrosity', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [105] = { title = 'Mog Gardens', description = 'Mog gardens / Entering your mog garden / Mog garden activities', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [106] = { title = 'Monster Rearing', description = 'Learn about monster rearing', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [131] = { title = 'Orb Battlefields', description = 'Orb Battlefields / Obtaining seals / Exchanging orbs', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xE4 },
    [135] = { title = 'Assault', description = 'Assault / Commissions Agency', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xC0 },
    [136] = { title = 'Nyzul Isle Investigation', description = 'Learn about the Nyzul Isle Investigation', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xFC },
    [137] = { title = 'Salvage', description = 'Learn about Salvage', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xC0 },
    [138] = { title = 'Campaign', description = 'Campaign / Alliance quests', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [140] = { title = 'Walk of Echoes', description = 'Learn about Walk of Echoes', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [143] = { title = 'Abyssea', description = 'Abyssea / Visitant / Abyssite / Atma', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xC0 },
    [145] = { title = 'Meeble Burrows', description = 'Meeble Burrows / Obtaining a grimoire / Moblin pheromone sacks and grimoire pages / Expeditions / Choosing an expedition / Entering the tunnels', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [146] = { title = 'Reives', description = 'Reives / Colonization reives / Lair reives / Wildskeeper reives', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xC0 },
    [147] = { title = 'Wanted Objectives', description = 'Learn about Wanted objectives', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xE4 },
    [148] = { title = 'Avatar Battlefields', description = 'Learn about avatar battlefields', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xE4 },
    [171] = { title = 'High-Tier Mission Battlefields', description = 'Learn about high-tier mission battlefields', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0x108 },
    [172] = { title = 'Nyzul Isle Uncharted Area Survey', description = 'Nyzul Isle Uncharted Area Survey / Making progress', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0x114 },
    [173] = { title = 'Salvage II', description = 'Learn about Salvage II', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [177] = { title = 'Skirmish', description = 'Learn about Skirmishes', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [178] = { title = 'Delve', description = 'Learn about Delve', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xC0 },
    [179] = { title = 'Alluvion Skirmish', description = 'Learn about Alluvion Skirmishes', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xE4 },
    [180] = { title = 'Incursion', description = 'Learn about Incursion', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [181] = { title = 'Vagary', description = 'Learn about Vagary', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xC0 },
    [182] = { title = 'Geas Fete', description = 'Learn about Geas Fete', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xCC },
    [183] = { title = 'Sinister Reign', description = 'Learn about Sinister Reign', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
    [184] = { title = 'Domain Invasion', description = 'Learn about Domain Invasion', source = 'dat:ROM/332/48.DAT rotate-right-5', title_offset = 0x50, description_offset = 0xD8 },
}
