-- Generated by tools/objective_guides/route_evidence.py. Do not edit.
local policy = {
  schema_version = 2,
  policy_revision = "objective-route-proof-v2.1",
  policy_sha256 = "87f2f0112976dc3423fbe5d7bcda1f4f1416ec4f33d7410d47785a08c9cf7c5a",
  probe_protocol = "accessxi-navprobe-jsonl-v2",
  probe_schema = 2,
  thresholds = {
    endpoint_epsilon_yalms = 0.75,
    maximum_segment_length_yalms = 80.0,
    maximum_waypoint_count = 65536,
    minimum_endpoint_clearance_yalms = 0.5,
    minimum_waypoint_clearance_yalms = 0.25,
    transition_corridor_radius_yalms = 3.0,
  },
  fixtures = {
    ["exact-two-point"] = { ["expect"] = "mesh-proven", ["id"] = "exact-two-point", ["observation"] = { ["end_clearance"] = 1.0, ["end_valid"] = true, ["fallback_used"] = false, ["first_endpoint_error"] = 0.0, ["last_endpoint_error"] = 0.0, ["minimum_waypoint_clearance"] = 1.0, ["path_length"] = 1.0, ["start_clearance"] = 1.0, ["start_valid"] = true, ["status"] = "exact-path", ["waypoint_count"] = 2, ["waypoints"] = { { ["clearance"] = 1.0, ["x"] = 0.0, ["y"] = 0.0, ["z"] = 0.0 }, { ["clearance"] = 1.0, ["x"] = 1.0, ["y"] = 0.0, ["z"] = 0.0 } } }, ["request"] = { ["end"] = { ["x"] = 1.0, ["y"] = 0.0, ["z"] = 0.0 }, ["start"] = { ["x"] = 0.0, ["y"] = 0.0, ["z"] = 0.0 } } },
    ["invalid-end-exit-zero"] = { ["expect"] = "end-invalid", ["id"] = "invalid-end-exit-zero", ["observation"] = { ["end_clearance"] = 1.0, ["end_valid"] = false, ["fallback_used"] = false, ["first_endpoint_error"] = 0.0, ["last_endpoint_error"] = 0.0, ["minimum_waypoint_clearance"] = 1.0, ["path_length"] = 0.0, ["start_clearance"] = 1.0, ["start_valid"] = true, ["status"] = "exact-path", ["waypoint_count"] = 1, ["waypoints"] = { { ["clearance"] = 1.0, ["x"] = 0.0, ["y"] = 0.0, ["z"] = 0.0 } } }, ["request"] = { ["end"] = { ["x"] = 1.0, ["y"] = 0.0, ["z"] = 0.0 }, ["start"] = { ["x"] = 0.0, ["y"] = 0.0, ["z"] = 0.0 } } },
    ["one-waypoint"] = { ["expect"] = "too-few-waypoints", ["id"] = "one-waypoint", ["observation"] = { ["end_clearance"] = 1.0, ["end_valid"] = true, ["fallback_used"] = false, ["first_endpoint_error"] = 0.0, ["last_endpoint_error"] = 0.0, ["minimum_waypoint_clearance"] = 1.0, ["path_length"] = 0.0, ["start_clearance"] = 1.0, ["start_valid"] = true, ["status"] = "exact-path", ["waypoint_count"] = 1, ["waypoints"] = { { ["clearance"] = 1.0, ["x"] = 0.0, ["y"] = 0.0, ["z"] = 0.0 } } }, ["request"] = { ["end"] = { ["x"] = 1.0, ["y"] = 0.0, ["z"] = 0.0 }, ["start"] = { ["x"] = 0.0, ["y"] = 0.0, ["z"] = 0.0 } } },
    ["closest-fallback"] = { ["expect"] = "closest-path-forbidden", ["id"] = "closest-fallback", ["observation"] = { ["end_clearance"] = 1.0, ["end_valid"] = true, ["fallback_used"] = true, ["first_endpoint_error"] = 0.0, ["last_endpoint_error"] = 0.0, ["minimum_waypoint_clearance"] = 1.0, ["path_length"] = 1.0, ["start_clearance"] = 1.0, ["start_valid"] = true, ["status"] = "exact-path", ["waypoint_count"] = 2, ["waypoints"] = { { ["clearance"] = 1.0, ["x"] = 0.0, ["y"] = 0.0, ["z"] = 0.0 }, { ["clearance"] = 1.0, ["x"] = 1.0, ["y"] = 0.0, ["z"] = 0.0 } } }, ["request"] = { ["end"] = { ["x"] = 1.0, ["y"] = 0.0, ["z"] = 0.0 }, ["start"] = { ["x"] = 0.0, ["y"] = 0.0, ["z"] = 0.0 } } },
    ["snapped-end"] = { ["expect"] = "endpoint-error", ["id"] = "snapped-end", ["observation"] = { ["end_clearance"] = 1.0, ["end_valid"] = true, ["fallback_used"] = false, ["first_endpoint_error"] = 0.0, ["last_endpoint_error"] = 0.0, ["minimum_waypoint_clearance"] = 1.0, ["path_length"] = 2.0, ["start_clearance"] = 1.0, ["start_valid"] = true, ["status"] = "exact-path", ["waypoint_count"] = 2, ["waypoints"] = { { ["clearance"] = 1.0, ["x"] = 0.0, ["y"] = 0.0, ["z"] = 0.0 }, { ["clearance"] = 1.0, ["x"] = 2.0, ["y"] = 0.0, ["z"] = 0.0 } } }, ["request"] = { ["end"] = { ["x"] = 1.0, ["y"] = 0.0, ["z"] = 0.0 }, ["start"] = { ["x"] = 0.0, ["y"] = 0.0, ["z"] = 0.0 } } },
    ["low-clearance"] = { ["expect"] = "waypoint-clearance", ["id"] = "low-clearance", ["observation"] = { ["end_clearance"] = 1.0, ["end_valid"] = true, ["fallback_used"] = false, ["first_endpoint_error"] = 0.0, ["last_endpoint_error"] = 0.0, ["minimum_waypoint_clearance"] = 0.1, ["path_length"] = 1.0, ["start_clearance"] = 1.0, ["start_valid"] = true, ["status"] = "exact-path", ["waypoint_count"] = 3, ["waypoints"] = { { ["clearance"] = 1.0, ["x"] = 0.0, ["y"] = 0.0, ["z"] = 0.0 }, { ["clearance"] = 0.1, ["x"] = 0.5, ["y"] = 0.0, ["z"] = 0.0 }, { ["clearance"] = 1.0, ["x"] = 1.0, ["y"] = 0.0, ["z"] = 0.0 } } }, ["request"] = { ["end"] = { ["x"] = 1.0, ["y"] = 0.0, ["z"] = 0.0 }, ["start"] = { ["x"] = 0.0, ["y"] = 0.0, ["z"] = 0.0 } } },
    ["long-segment"] = { ["expect"] = "segment-too-long", ["id"] = "long-segment", ["observation"] = { ["end_clearance"] = 1.0, ["end_valid"] = true, ["fallback_used"] = false, ["first_endpoint_error"] = 0.0, ["last_endpoint_error"] = 0.0, ["minimum_waypoint_clearance"] = 1.0, ["path_length"] = 100.0, ["start_clearance"] = 1.0, ["start_valid"] = true, ["status"] = "exact-path", ["waypoint_count"] = 2, ["waypoints"] = { { ["clearance"] = 1.0, ["x"] = 0.0, ["y"] = 0.0, ["z"] = 0.0 }, { ["clearance"] = 1.0, ["x"] = 100.0, ["y"] = 0.0, ["z"] = 0.0 } } }, ["request"] = { ["end"] = { ["x"] = 100.0, ["y"] = 0.0, ["z"] = 0.0 }, ["start"] = { ["x"] = 0.0, ["y"] = 0.0, ["z"] = 0.0 } } },
  },
}
local function distance(a, b)
  local dx, dz, dy = a.x - b.x, a.z - b.z, a.y - b.y
  return math.sqrt(dx * dx + dz * dz + dy * dy)
end
local function classify_case(request, row)
  if not row.start_valid then return 'start-invalid' end
  if not row.end_valid then return 'end-invalid' end
  if row.fallback_used then return 'closest-path-forbidden' end
  if row.status ~= 'exact-path' then return 'no-exact-path' end
  if row.waypoint_count > policy.thresholds.maximum_waypoint_count then return 'waypoint-count-excessive' end
  if row.waypoint_count ~= #row.waypoints then return 'waypoint-count-mismatch' end
  if #row.waypoints < 2 then return 'too-few-waypoints' end
  local first, last = row.waypoints[1], row.waypoints[#row.waypoints]
  local actual_first, actual_last = distance(request.start, first), distance(request['end'], last)
  if math.max(actual_first, actual_last, row.first_endpoint_error, row.last_endpoint_error) > policy.thresholds.endpoint_epsilon_yalms then return 'endpoint-error' end
  if math.abs(actual_first - row.first_endpoint_error) > 0.000001 or math.abs(actual_last - row.last_endpoint_error) > 0.000001 then return 'endpoint-error-recomputed' end
  local minimum = first.clearance
  for _, waypoint in ipairs(row.waypoints) do if waypoint.clearance < minimum then minimum = waypoint.clearance end end
  if math.abs(minimum - row.minimum_waypoint_clearance) > 0.000001 then return 'waypoint-clearance-recomputed' end
  if minimum < policy.thresholds.minimum_waypoint_clearance_yalms then return 'waypoint-clearance' end
  if math.min(row.start_clearance, row.end_clearance, first.clearance, last.clearance) < policy.thresholds.minimum_endpoint_clearance_yalms then return 'endpoint-clearance' end
  local length = 0
  for index = 2, #row.waypoints do
    local segment = distance(row.waypoints[index - 1], row.waypoints[index])
    if segment > policy.thresholds.maximum_segment_length_yalms then return 'segment-too-long' end
    length = length + segment
  end
  if math.abs(length - row.path_length) > 0.000000001 then return 'path-length-mismatch' end
  return 'mesh-proven'
end
policy.classify_case = classify_case
function policy.classify_fixture(id)
  local fixture = policy.fixtures[id]
  if fixture == nil then return nil end
  return classify_case(fixture.request, fixture.observation)
end
return policy
