-- Generated AccessXI reconciliation facts. Do not edit by hand.
-- No source walkthrough prose is combined in this module.
return {
  ["mission:A Crystalline Prophecy:1"] = {
    dynamic_candidate_comparison = "none",
    dynamic_candidate_grid = {  },
    selected_candidate_grid = nil,
    default_step_id = nil,
    automatic_stages = {
    },
    steps = {
      {
        stable_step_id = "mission:A Crystalline Prophecy:1:step-001",
        order = 1,
        source_orders = { 1, 1 },
        comparison = "corroborated",
        agreed_fields = { "action", "entities" },
        conflicting_fields = {  },
        action = "travel",
        entities = { "Lower Jeuno" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:1:step-002",
        order = 2,
        source_orders = { 0, 2 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "travel",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:1:step-003",
        order = 3,
        source_orders = { 0, 3 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "obtain",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:1:step-004",
        order = 4,
        source_orders = { 0, 4 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "The Echo Awakens" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
    },
  },
  ["mission:A Crystalline Prophecy:10"] = {
    dynamic_candidate_comparison = "none",
    dynamic_candidate_grid = {  },
    selected_candidate_grid = nil,
    default_step_id = nil,
    automatic_stages = {
    },
    steps = {
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-001",
        order = 1,
        source_orders = { 1, 1 },
        comparison = "conflict",
        agreed_fields = { "entities" },
        conflicting_fields = { "action" },
        action = "examine",
        entities = { "Seed Fragment", "Key Items", "Seed Afterglow", "Lower Delkfutt's Tower" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-002",
        order = 2,
        source_orders = { 0, 2 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-003",
        order = 3,
        source_orders = { 2, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-004",
        order = 4,
        source_orders = { 3, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Trust Magic" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-005",
        order = 5,
        source_orders = { 4, 3 },
        comparison = "corroborated",
        agreed_fields = { "action" },
        conflicting_fields = {  },
        action = "use",
        entities = { "Destrier Beret", "Dancer", "Spectral Jig" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-006",
        order = 6,
        source_orders = { 0, 4 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "travel",
        entities = { "Stellar Fulcrum" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-007",
        order = 7,
        source_orders = { 0, 5 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-008",
        order = 8,
        source_orders = { 0, 6 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "trade",
        entities = { "Seed Afterglow" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-009",
        order = 9,
        source_orders = { 5, 7 },
        comparison = "conflict",
        agreed_fields = { "entities" },
        conflicting_fields = { "action" },
        action = "examine",
        entities = { "Sprinter's Shoes", "Seed Fragment" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-010",
        order = 10,
        source_orders = { 0, 8 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "K.O." },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-011",
        order = 11,
        source_orders = { 0, 9 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "obtain",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-012",
        order = 12,
        source_orders = { 0, 10 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-013",
        order = 13,
        source_orders = { 0, 11 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Tractor" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-014",
        order = 14,
        source_orders = { 6, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Prism Powder", "Silent Oil", "Doll", "Elemental" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-015",
        order = 15,
        source_orders = { 7, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "examine",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-016",
        order = 16,
        source_orders = { 8, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-017",
        order = 17,
        source_orders = { 9, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-018",
        order = 18,
        source_orders = { 10, 12 },
        comparison = "corroborated",
        agreed_fields = { "action" },
        conflicting_fields = {  },
        action = "examine",
        entities = { "Stellar Fulcrum", "Omnis stone" },
        zones = {  },
        grid_coordinates = { "H-10" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-019",
        order = 19,
        source_orders = { 0, 13 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "travel",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-020",
        order = 20,
        source_orders = { 0, 14 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "obtain",
        entities = { "Omnis stone", "Squintrox Dryeyes", "Port Jeuno", "A Crystalline Prophecy" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-021",
        order = 21,
        source_orders = { 11, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "examine",
        entities = { "Amicitia Stone" },
        zones = {  },
        grid_coordinates = { "J-10" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-022",
        order = 22,
        source_orders = { 12, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "examine",
        entities = { "Veritas Stone" },
        zones = {  },
        grid_coordinates = { "H-7" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-023",
        order = 23,
        source_orders = { 13, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "examine",
        entities = { "Sapientia Stone" },
        zones = {  },
        grid_coordinates = { "I-9" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-024",
        order = 24,
        source_orders = { 14, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = { "G-6" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-025",
        order = 25,
        source_orders = { 15, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-026",
        order = 26,
        source_orders = { 16, 15 },
        comparison = "corroborated",
        agreed_fields = { "action" },
        conflicting_fields = {  },
        action = "examine",
        entities = {  },
        zones = {  },
        grid_coordinates = { "G-6" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-027",
        order = 27,
        source_orders = { 0, 16 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Mathilde", "Selbina" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-028",
        order = 28,
        source_orders = { 0, 17 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Prism Powder", "Silent Oil" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-029",
        order = 29,
        source_orders = { 17, 18 },
        comparison = "corroborated",
        agreed_fields = { "action" },
        conflicting_fields = {  },
        action = "examine",
        entities = { "Sanctitas Stone" },
        zones = {  },
        grid_coordinates = { "H-10" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-030",
        order = 30,
        source_orders = { 0, 19 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Delkfutt's Tower" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-031",
        order = 31,
        source_orders = { 18, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "examine",
        entities = { "Felicitas Stone" },
        zones = {  },
        grid_coordinates = { "G-7" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-032",
        order = 32,
        source_orders = { 19, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "examine",
        entities = { "Divitia Stone" },
        zones = {  },
        grid_coordinates = { "F-8" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-033",
        order = 33,
        source_orders = { 20, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "examine",
        entities = { "Studium Stone" },
        zones = {  },
        grid_coordinates = { "H-9" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-034",
        order = 34,
        source_orders = { 21, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "examine",
        entities = { "Amoris Stone" },
        zones = {  },
        grid_coordinates = { "I-8" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-035",
        order = 35,
        source_orders = { 22, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "examine",
        entities = { "Caritas Stone" },
        zones = {  },
        grid_coordinates = { "G-8" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-036",
        order = 36,
        source_orders = { 23, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = { "F-6" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-037",
        order = 37,
        source_orders = { 24, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-038",
        order = 38,
        source_orders = { 25, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "examine",
        entities = {  },
        zones = {  },
        grid_coordinates = { "F-7" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-039",
        order = 39,
        source_orders = { 26, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "examine",
        entities = { "Constantia Stone" },
        zones = {  },
        grid_coordinates = { "F-10" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-040",
        order = 40,
        source_orders = { 27, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "examine",
        entities = { "Spei Stone" },
        zones = {  },
        grid_coordinates = { "H-7" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-041",
        order = 41,
        source_orders = { 28, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "examine",
        entities = { "Salus Stone" },
        zones = {  },
        grid_coordinates = { "H-7" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-042",
        order = 42,
        source_orders = { 29, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Stellar Fulcrum" },
        zones = {  },
        grid_coordinates = { "F-10" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:10:step-043",
        order = 43,
        source_orders = { 30, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "examine",
        entities = { "Omnis Stone" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
    },
  },
  ["mission:A Crystalline Prophecy:11"] = {
    dynamic_candidate_comparison = "none",
    dynamic_candidate_grid = {  },
    selected_candidate_grid = nil,
    default_step_id = nil,
    automatic_stages = {
    },
    steps = {
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-001",
        order = 1,
        source_orders = { 1, 1 },
        comparison = "corroborated",
        agreed_fields = { "action" },
        conflicting_fields = {  },
        action = "examine",
        entities = { "Stellar Fulcrum" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-002",
        order = 2,
        source_orders = { 0, 2 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Upper Delkfutt's Tower" },
        zones = {  },
        grid_coordinates = { "F-10" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-003",
        order = 3,
        source_orders = { 2, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "examine",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-004",
        order = 4,
        source_orders = { 3, 3 },
        comparison = "corroborated",
        agreed_fields = { "action" },
        conflicting_fields = {  },
        action = "fight",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-005",
        order = 5,
        source_orders = { 0, 4 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-006",
        order = 6,
        source_orders = { 0, 5 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-007",
        order = 7,
        source_orders = { 0, 6 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Omnis stone" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-008",
        order = 8,
        source_orders = { 0, 7 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "obtain",
        entities = { "Ebon Key", "Omnis stone" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-009",
        order = 9,
        source_orders = { 4, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Seed Crystal" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-010",
        order = 10,
        source_orders = { 5, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Draw-In" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-011",
        order = 11,
        source_orders = { 6, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-012",
        order = 12,
        source_orders = { 7, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-013",
        order = 13,
        source_orders = { 8, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Stonega III", "Waterga III", "Aeroga III", "Thundaga III", "Firaga III", "Blizzaga III" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-014",
        order = 14,
        source_orders = { 9, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Draw In" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-015",
        order = 15,
        source_orders = { 10, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-016",
        order = 16,
        source_orders = { 11, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "2hr abilities" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-017",
        order = 17,
        source_orders = { 12, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Charm", "Seed Mandragora" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-018",
        order = 18,
        source_orders = { 13, 8 },
        comparison = "corroborated",
        agreed_fields = { "action" },
        conflicting_fields = {  },
        action = "fight",
        entities = { "Omnis stone" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-019",
        order = 19,
        source_orders = { 0, 9 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "obtain",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:11:step-020",
        order = 20,
        source_orders = { 14, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
    },
  },
  ["mission:A Crystalline Prophecy:12"] = {
    dynamic_candidate_comparison = "none",
    dynamic_candidate_grid = {  },
    selected_candidate_grid = nil,
    default_step_id = nil,
    automatic_stages = {
    },
    steps = {
      {
        stable_step_id = "mission:A Crystalline Prophecy:12:step-001",
        order = 1,
        source_orders = { 1, 1 },
        comparison = "corroborated",
        agreed_fields = { "action", "entities" },
        conflicting_fields = {  },
        action = "examine",
        entities = { "Tenshodo", "Lower Jeuno", "Treasure Coffer" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:12:step-002",
        order = 2,
        source_orders = { 0, 2 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Nuevo Coselete", "Mirke Wardecors", "Royal Redingote" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:12:step-003",
        order = 3,
        source_orders = { 2, 3 },
        comparison = "corroborated",
        agreed_fields = { "action", "entities" },
        conflicting_fields = {  },
        action = "fight",
        entities = { "Omnis Stone", "Squintrox Dryeyes", "Port Jeuno", "Beastmen Seals", "Stellar Fulcrum", "Ode of Life Bestowing", "Ebon Key" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
    },
  },
  ["mission:A Crystalline Prophecy:2"] = {
    dynamic_candidate_comparison = "none",
    dynamic_candidate_grid = {  },
    selected_candidate_grid = nil,
    default_step_id = nil,
    automatic_stages = {
    },
    steps = {
      {
        stable_step_id = "mission:A Crystalline Prophecy:2:step-001",
        order = 1,
        source_orders = { 1, 1 },
        comparison = "corroborated",
        agreed_fields = { "action" },
        conflicting_fields = {  },
        action = "obtain",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:2:step-002",
        order = 2,
        source_orders = { 2, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Seedspall Lux", "Orcs", "Jugner Forest" },
        zones = {  },
        grid_coordinates = { "G-11" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:2:step-003",
        order = 3,
        source_orders = { 3, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Survival Guide", "Davoi" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:2:step-004",
        order = 4,
        source_orders = { 4, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Seedspall Luna", "Quadavs", "Pashhow Marshlands" },
        zones = {  },
        grid_coordinates = { "K-10" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:2:step-005",
        order = 5,
        source_orders = { 5, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Survival Guide", "Beadeaux" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:2:step-006",
        order = 6,
        source_orders = { 6, 2 },
        comparison = "corroborated",
        agreed_fields = { "action", "entities" },
        conflicting_fields = {  },
        action = "note",
        entities = { "Seedspall Astrum", "Yagudos", "Meriphataud Mountains", "Yagudo" },
        zones = {  },
        grid_coordinates = { "K-8" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:2:step-007",
        order = 7,
        source_orders = { 7, 3 },
        comparison = "corroborated",
        agreed_fields = { "action", "entities" },
        conflicting_fields = {  },
        action = "note",
        entities = { "Survival Guide", "Castle Oztroja" },
        zones = {  },
        grid_coordinates = { "K-8" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:2:step-008",
        order = 8,
        source_orders = { 0, 4 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Seedspall Luna", "Quadav", "Pashhow Marshlands" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:2:step-009",
        order = 9,
        source_orders = { 0, 5 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Beadeaux" },
        zones = {  },
        grid_coordinates = { "K-10" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:2:step-010",
        order = 10,
        source_orders = { 0, 6 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Seedspall Lux", "Orcs", "Jugner Forest" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:2:step-011",
        order = 11,
        source_orders = { 0, 7 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Davoi" },
        zones = {  },
        grid_coordinates = { "G-11" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:2:step-012",
        order = 12,
        source_orders = { 8, 8 },
        comparison = "corroborated",
        agreed_fields = { "action", "grid_coordinates", "entities" },
        conflicting_fields = {  },
        action = "trade",
        entities = { "Qufim Island", "???" },
        zones = {  },
        grid_coordinates = { "G-6" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:2:step-013",
        order = 13,
        source_orders = { 9, 9 },
        comparison = "conflict",
        agreed_fields = { "action" },
        conflicting_fields = { "grid_coordinates" },
        action = "note",
        entities = { "???" },
        zones = {  },
        grid_coordinates = { "G-6", "H-6" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:2:step-014",
        order = 14,
        source_orders = { 0, 10 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:2:step-015",
        order = 15,
        source_orders = { 0, 11 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "trade",
        entities = { "Squintrox Dryeyes", "Port Jeuno", "Crimson Key" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:2:step-016",
        order = 16,
        source_orders = { 0, 12 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:2:step-017",
        order = 17,
        source_orders = { 0, 13 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Qufim Island", "Chains of Promathia" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
    },
  },
  ["mission:A Crystalline Prophecy:3"] = {
    dynamic_candidate_comparison = "none",
    dynamic_candidate_grid = {  },
    selected_candidate_grid = nil,
    default_step_id = nil,
    automatic_stages = {
    },
    steps = {
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-001",
        order = 1,
        source_orders = { 1, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "obtain",
        entities = { "Goblin", "Notorious Monsters" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-002",
        order = 2,
        source_orders = { 2, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "obtain",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-003",
        order = 3,
        source_orders = { 3, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "obtain",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-004",
        order = 4,
        source_orders = { 4, 1 },
        comparison = "corroborated",
        agreed_fields = { "action" },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-005",
        order = 5,
        source_orders = { 5, 2 },
        comparison = "conflict",
        agreed_fields = { "entities", "key_items" },
        conflicting_fields = { "action" },
        action = "fight",
        entities = { "Batallia Downs", "Bowl of bland Goblin salad", "Norvallen" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-006",
        order = 6,
        source_orders = { 6, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-007",
        order = 7,
        source_orders = { 7, 3 },
        comparison = "conflict",
        agreed_fields = { "grid_coordinates", "entities", "key_items" },
        conflicting_fields = { "action" },
        action = "examine",
        entities = { "Vegnix Greenthumb", "Seedspall Roseum" },
        zones = {  },
        grid_coordinates = { "F-5" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-008",
        order = 8,
        source_orders = { 8, 4 },
        comparison = "corroborated",
        agreed_fields = { "entities" },
        conflicting_fields = {  },
        action = "note",
        entities = { "Beaucedine Glacier", "Lycopodium (NPC)" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-009",
        order = 9,
        source_orders = { 9, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "trade",
        entities = { "Lycopodium Warps" },
        zones = {  },
        grid_coordinates = { "F-5" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-010",
        order = 10,
        source_orders = { 10, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "obtain",
        entities = { "Survival Guide" },
        zones = {  },
        grid_coordinates = { "H-9", "H-11" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-011",
        order = 11,
        source_orders = { 11, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Voidwatch", "Adventurer's Certificate", "Ranguemont Pass" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-012",
        order = 12,
        source_orders = { 12, 5 },
        comparison = "corroborated",
        agreed_fields = { "action" },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-013",
        order = 13,
        source_orders = { 13, 6 },
        comparison = "conflict",
        agreed_fields = { "entities", "key_items" },
        conflicting_fields = { "action" },
        action = "fight",
        entities = { "Rolanberry Fields", "Jug of greasy Goblin juice" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-014",
        order = 14,
        source_orders = { 14, 7 },
        comparison = "conflict",
        agreed_fields = { "grid_coordinates", "entities", "key_items" },
        conflicting_fields = { "action" },
        action = "examine",
        entities = { "Chuglix Berrypaws", "Seedspall Caerulum" },
        zones = {  },
        grid_coordinates = { "D-11" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-015",
        order = 15,
        source_orders = { 15, 8 },
        comparison = "corroborated",
        agreed_fields = { "entities" },
        conflicting_fields = {  },
        action = "note",
        entities = { "Crawlers' Nest", "Unity Concord NPC" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-016",
        order = 16,
        source_orders = { 16, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "obtain",
        entities = { "Unity Warp 125" },
        zones = {  },
        grid_coordinates = { "D-11" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-017",
        order = 17,
        source_orders = { 17, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Simurgh" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-018",
        order = 18,
        source_orders = { 18, 9 },
        comparison = "corroborated",
        agreed_fields = { "action" },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-019",
        order = 19,
        source_orders = { 19, 10 },
        comparison = "conflict",
        agreed_fields = { "entities", "key_items" },
        conflicting_fields = { "action" },
        action = "fight",
        entities = { "Sauromugue Champaign", "Chunk of smoked Goblin grub" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-020",
        order = 20,
        source_orders = { 20, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-021",
        order = 21,
        source_orders = { 21, 11 },
        comparison = "conflict",
        agreed_fields = { "entities", "key_items" },
        conflicting_fields = { "action", "grid_coordinates" },
        action = "examine",
        entities = { "Dribblix Greasemaw", "Seedspall Viridis" },
        zones = {  },
        grid_coordinates = { "J-9", "I-9", "I-10", "J-10" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-022",
        order = 22,
        source_orders = { 0, 12 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "use",
        entities = { "Garlaige Citadel", "Atmacite Refiner", "Cavernous Maw", "Garlaige Citadel (S)" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-023",
        order = 23,
        source_orders = { 22, 13 },
        comparison = "conflict",
        agreed_fields = {  },
        conflicting_fields = { "grid_coordinates" },
        action = "obtain",
        entities = { "Sauromugue Champaign", "Cavernous Maw" },
        zones = {  },
        grid_coordinates = { "J-10", "J-9" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-024",
        order = 24,
        source_orders = { 0, 14 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-025",
        order = 25,
        source_orders = { 23, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Roc", "Voidwatch" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-026",
        order = 26,
        source_orders = { 24, 15 },
        comparison = "conflict",
        agreed_fields = { "grid_coordinates", "entities" },
        conflicting_fields = { "action" },
        action = "examine",
        entities = { "Qufim Island" },
        zones = {  },
        grid_coordinates = { "G-6" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-027",
        order = 27,
        source_orders = { 0, 16 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-028",
        order = 28,
        source_orders = { 0, 17 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-029",
        order = 29,
        source_orders = { 0, 18 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "obtain",
        entities = { "Monipulator" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-030",
        order = 30,
        source_orders = { 0, 19 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "fight",
        entities = { "Viridian Key" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-031",
        order = 31,
        source_orders = { 0, 20 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "obtain",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-032",
        order = 32,
        source_orders = { 0, 21 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-033",
        order = 33,
        source_orders = { 0, 22 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "obtain",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-034",
        order = 34,
        source_orders = { 0, 23 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "obtain",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-035",
        order = 35,
        source_orders = { 0, 24 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-036",
        order = 36,
        source_orders = { 0, 25 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:3:step-037",
        order = 37,
        source_orders = { 0, 26 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Squintrox Dryeyes", "Viridian Key" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
    },
  },
  ["mission:A Crystalline Prophecy:4"] = {
    dynamic_candidate_comparison = "none",
    dynamic_candidate_grid = {  },
    selected_candidate_grid = nil,
    default_step_id = nil,
    automatic_stages = {
    },
    steps = {
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-001",
        order = 1,
        source_orders = { 1, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "fight",
        entities = { "Trust Magic" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-002",
        order = 2,
        source_orders = { 2, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-003",
        order = 3,
        source_orders = { 3, 1 },
        comparison = "corroborated",
        agreed_fields = { "action" },
        conflicting_fields = {  },
        action = "examine",
        entities = { "Qufim Island", "???", "Confrontation" },
        zones = {  },
        grid_coordinates = { "G-6" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-004",
        order = 4,
        source_orders = { 0, 2 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "fight",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-005",
        order = 5,
        source_orders = { 0, 3 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "fight",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-006",
        order = 6,
        source_orders = { 0, 4 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "fight",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-007",
        order = 7,
        source_orders = { 0, 5 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "fight",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-008",
        order = 8,
        source_orders = { 0, 6 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "fight",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-009",
        order = 9,
        source_orders = { 0, 7 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "fight",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-010",
        order = 10,
        source_orders = { 0, 8 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "wait",
        entities = { "Viridian Key" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-011",
        order = 11,
        source_orders = { 0, 9 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "fight",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-012",
        order = 12,
        source_orders = { 4, 10 },
        comparison = "corroborated",
        agreed_fields = { "action", "entities" },
        conflicting_fields = {  },
        action = "note",
        entities = { "Seed Mandragora" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-013",
        order = 13,
        source_orders = { 0, 11 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-014",
        order = 14,
        source_orders = { 0, 12 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Plantoid Killer" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-015",
        order = 15,
        source_orders = { 0, 13 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-016",
        order = 16,
        source_orders = { 0, 14 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "use",
        entities = { "Demonic Flower", "Souleater" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-017",
        order = 17,
        source_orders = { 0, 15 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-018",
        order = 18,
        source_orders = { 0, 16 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-019",
        order = 19,
        source_orders = { 0, 17 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "fight",
        entities = { "/autotarget" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-020",
        order = 20,
        source_orders = { 0, 18 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "fight",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-021",
        order = 21,
        source_orders = { 0, 19 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "fight",
        entities = { "Dragoon Wyvern" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-022",
        order = 22,
        source_orders = { 0, 20 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "fight",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-023",
        order = 23,
        source_orders = { 0, 21 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "fight",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-024",
        order = 24,
        source_orders = { 0, 22 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "fight",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-025",
        order = 25,
        source_orders = { 5, 23 },
        comparison = "conflict",
        agreed_fields = { "entities", "key_items" },
        conflicting_fields = { "action" },
        action = "obtain",
        entities = { "Amber Key" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-026",
        order = 26,
        source_orders = { 6, 24 },
        comparison = "corroborated",
        agreed_fields = { "action" },
        conflicting_fields = {  },
        action = "examine",
        entities = { "???" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-027",
        order = 27,
        source_orders = { 0, 25 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:4:step-028",
        order = 28,
        source_orders = { 0, 26 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "fight",
        entities = { "Amber Key" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
    },
  },
  ["mission:A Crystalline Prophecy:5"] = {
    dynamic_candidate_comparison = "none",
    dynamic_candidate_grid = {  },
    selected_candidate_grid = nil,
    default_step_id = nil,
    automatic_stages = {
    },
    steps = {
      {
        stable_step_id = "mission:A Crystalline Prophecy:5:step-001",
        order = 1,
        source_orders = { 1, 1 },
        comparison = "corroborated",
        agreed_fields = { "action", "entities" },
        conflicting_fields = {  },
        action = "travel",
        entities = { "Fei'Yin", "Beaucedine Glacier" },
        zones = {  },
        grid_coordinates = { "J-4" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:5:step-002",
        order = 2,
        source_orders = { 0, 2 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "travel",
        entities = { "Fei'Yin", "Cloister of Frost", "Summoner" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:5:step-003",
        order = 3,
        source_orders = { 0, 3 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "use",
        entities = { "Domenic", "Lower Jeuno", "Qu'Bia Arena" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:5:step-004",
        order = 4,
        source_orders = { 0, 4 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "use",
        entities = { "Home Point", "Qu'Bia Arena" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
    },
  },
  ["mission:A Crystalline Prophecy:6"] = {
    dynamic_candidate_comparison = "none",
    dynamic_candidate_grid = {  },
    selected_candidate_grid = nil,
    default_step_id = nil,
    automatic_stages = {
    },
    steps = {
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-001",
        order = 1,
        source_orders = { 1, 1 },
        comparison = "corroborated",
        agreed_fields = { "entities" },
        conflicting_fields = {  },
        action = "note",
        entities = { "Seed Afterglow", "Fei'Yin" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-002",
        order = 2,
        source_orders = { 0, 2 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-003",
        order = 3,
        source_orders = { 0, 3 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-004",
        order = 4,
        source_orders = { 0, 4 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-005",
        order = 5,
        source_orders = { 0, 5 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "obtain",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-006",
        order = 6,
        source_orders = { 2, 6 },
        comparison = "corroborated",
        agreed_fields = { "action" },
        conflicting_fields = {  },
        action = "obtain",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-007",
        order = 7,
        source_orders = { 0, 7 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Fei'Yin" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-008",
        order = 8,
        source_orders = { 0, 8 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Fei'Yin" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-009",
        order = 9,
        source_orders = { 3, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-010",
        order = 10,
        source_orders = { 4, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = { "I-9" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-011",
        order = 11,
        source_orders = { 5, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-012",
        order = 12,
        source_orders = { 6, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = { "K-8" },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-013",
        order = 13,
        source_orders = { 7, 9 },
        comparison = "corroborated",
        agreed_fields = { "entities" },
        conflicting_fields = {  },
        action = "obtain",
        entities = { "Mark of Seed", "Azure Key" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-014",
        order = 14,
        source_orders = { 0, 10 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "travel",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-015",
        order = 15,
        source_orders = { 0, 11 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "travel",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-016",
        order = 16,
        source_orders = { 0, 12 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "wait",
        entities = { "Treasure Coffer" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-017",
        order = 17,
        source_orders = { 0, 13 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "talk",
        entities = { "Mark of Seed" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-018",
        order = 18,
        source_orders = { 0, 14 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "travel",
        entities = { "Azure Key", "Seed Afterglow" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-019",
        order = 19,
        source_orders = { 0, 15 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "obtain",
        entities = { "Mark of Seed", "Squintrox Dryeyes", "Port Jeuno", "A Crystalline Prophecy" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-020",
        order = 20,
        source_orders = { 0, 16 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Mark of Seed", "Qu'Bia Arena" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-021",
        order = 21,
        source_orders = { 0, 17 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "use",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-022",
        order = 22,
        source_orders = { 8, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:6:step-023",
        order = 23,
        source_orders = { 9, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Add-on Scenario Rewards#Azure Key{{!}}Add-on Scenario Rewards" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
    },
  },
  ["mission:A Crystalline Prophecy:7"] = {
    dynamic_candidate_comparison = "none",
    dynamic_candidate_grid = {  },
    selected_candidate_grid = nil,
    default_step_id = nil,
    automatic_stages = {
    },
    steps = {
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-001",
        order = 1,
        source_orders = { 0, 1 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "fight",
        entities = { "Mark of Seed" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-002",
        order = 2,
        source_orders = { 0, 2 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Ivory Key" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-003",
        order = 3,
        source_orders = { 0, 3 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Mark of Seed", "Squintrox Dryeyes", "Port Jeuno", "Beastmen's Seal", "A Crystalline Prophecy" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-004",
        order = 4,
        source_orders = { 1, 4 },
        comparison = "corroborated",
        agreed_fields = { "action", "entities" },
        conflicting_fields = {  },
        action = "examine",
        entities = { "Qu'Bia Arena" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-005",
        order = 5,
        source_orders = { 0, 5 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Level Restriction" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-006",
        order = 6,
        source_orders = { 0, 6 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-007",
        order = 7,
        source_orders = { 0, 7 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-008",
        order = 8,
        source_orders = { 0, 8 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Tractor" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-009",
        order = 9,
        source_orders = { 0, 9 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-010",
        order = 10,
        source_orders = { 0, 10 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-011",
        order = 11,
        source_orders = { 2, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "fight",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-012",
        order = 12,
        source_orders = { 3, 11 },
        comparison = "corroborated",
        agreed_fields = { "action" },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-013",
        order = 13,
        source_orders = { 0, 12 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Seed Orc" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-014",
        order = 14,
        source_orders = { 4, 13 },
        comparison = "corroborated",
        agreed_fields = { "action", "entities" },
        conflicting_fields = {  },
        action = "note",
        entities = { "Seed Yagudo" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-015",
        order = 15,
        source_orders = { 5, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Bind" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-016",
        order = 16,
        source_orders = { 6, 14 },
        comparison = "corroborated",
        agreed_fields = { "action", "entities" },
        conflicting_fields = {  },
        action = "note",
        entities = { "Seed Quadav" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-017",
        order = 17,
        source_orders = { 7, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Bio" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-018",
        order = 18,
        source_orders = { 8, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Seed Orc" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-019",
        order = 19,
        source_orders = { 9, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Curse", "Plague" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-020",
        order = 20,
        source_orders = { 10, 15 },
        comparison = "corroborated",
        agreed_fields = { "action", "entities" },
        conflicting_fields = {  },
        action = "note",
        entities = { "Seed Goblin" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-021",
        order = 21,
        source_orders = { 11, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-022",
        order = 22,
        source_orders = { 12, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-023",
        order = 23,
        source_orders = { 13, 16 },
        comparison = "corroborated",
        agreed_fields = { "action" },
        conflicting_fields = {  },
        action = "fight",
        entities = { "Mark of Seed" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-024",
        order = 24,
        source_orders = { 0, 17 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "wait",
        entities = {  },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-025",
        order = 25,
        source_orders = { 14, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "note",
        entities = { "Sneak Attack", "Trick Attack", "Bomb Toss" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:7:step-026",
        order = 26,
        source_orders = { 15, 18 },
        comparison = "corroborated",
        agreed_fields = { "action", "entities" },
        conflicting_fields = {  },
        action = "fight",
        entities = { "Ivory Key", "Treasure Coffer (Tenshodo)", "Mark of Seed" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
    },
  },
  ["mission:A Crystalline Prophecy:8"] = {
    dynamic_candidate_comparison = "none",
    dynamic_candidate_grid = {  },
    selected_candidate_grid = nil,
    default_step_id = nil,
    automatic_stages = {
    },
    steps = {
      {
        stable_step_id = "mission:A Crystalline Prophecy:8:step-001",
        order = 1,
        source_orders = { 1, 1 },
        comparison = "corroborated",
        agreed_fields = { "action", "entities" },
        conflicting_fields = {  },
        action = "travel",
        entities = { "Hall of the Gods", "Ro'Maeve" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:8:step-002",
        order = 2,
        source_orders = { 2, 2 },
        comparison = "corroborated",
        agreed_fields = { "entities" },
        conflicting_fields = {  },
        action = "travel",
        entities = { "Ru'Aun Gardens", "Ro'Maeve" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
      {
        stable_step_id = "mission:A Crystalline Prophecy:8:step-003",
        order = 3,
        source_orders = { 3, 0 },
        comparison = "single-source",
        agreed_fields = {  },
        conflicting_fields = {  },
        action = "obtain",
        entities = { "Survival Guide" },
        zones = {  },
        grid_coordinates = { "H-6" },
        route_ready = false,
      },
    },
  },
  ["mission:A Crystalline Prophecy:9"] = {
    dynamic_candidate_comparison = "none",
    dynamic_candidate_grid = {  },
    selected_candidate_grid = nil,
    default_step_id = nil,
    automatic_stages = {
    },
    steps = {
      {
        stable_step_id = "mission:A Crystalline Prophecy:9:step-001",
        order = 1,
        source_orders = { 1, 1 },
        comparison = "corroborated",
        agreed_fields = { "action", "entities" },
        conflicting_fields = {  },
        action = "travel",
        entities = { "Lower Delkfutt's Tower" },
        zones = {  },
        grid_coordinates = {  },
        route_ready = false,
      },
    },
  },
}
