local data = {};

data.packet_113_fields = T{
    { off = 0x00, size = 4, name = 'conquest_points_sandoria' },
    { off = 0x04, size = 4, name = 'conquest_points_bastok' },
    { off = 0x08, size = 4, name = 'conquest_points_windurst' },
    { off = 0x0C, size = 2, name = 'beastman_seals_stored' },
    { off = 0x0E, size = 2, name = 'kindred_seals_stored' },
    { off = 0x10, size = 2, name = 'kindred_crests_stored' },
    { off = 0x12, size = 2, name = 'high_kindred_crests_stored' },
    { off = 0x14, size = 2, name = 'sacred_kindred_crests_stored' },
    { off = 0x16, size = 2, name = 'ancient_beastcoins_stored' },
    { off = 0x18, size = 2, name = 'valor_points' },
    { off = 0x1A, size = 2, name = 'scylds' },
    { off = 0x1C, size = 4, name = 'guild_points_fishing' },
    { off = 0x20, size = 4, name = 'guild_points_woodworking' },
    { off = 0x24, size = 4, name = 'guild_points_smithing' },
    { off = 0x28, size = 4, name = 'guild_points_goldsmithing' },
    { off = 0x2C, size = 4, name = 'guild_points_weaving' },
    { off = 0x30, size = 4, name = 'guild_points_leathercraft' },
    { off = 0x34, size = 4, name = 'guild_points_bonecraft' },
    { off = 0x38, size = 4, name = 'guild_points_alchemy' },
    { off = 0x3C, size = 4, name = 'guild_points_cooking' },
    { off = 0x40, size = 4, name = 'cinders' },
    { off = 0x44, size = 1, name = 'synergy_fewell_fire' },
    { off = 0x45, size = 1, name = 'synergy_fewell_ice' },
    { off = 0x46, size = 1, name = 'synergy_fewell_wind' },
    { off = 0x47, size = 1, name = 'synergy_fewell_earth' },
    { off = 0x48, size = 1, name = 'synergy_fewell_lightning' },
    { off = 0x49, size = 1, name = 'synergy_fewell_water' },
    { off = 0x4A, size = 1, name = 'synergy_fewell_light' },
    { off = 0x4B, size = 1, name = 'synergy_fewell_dark' },
    { off = 0x4C, size = 4, name = 'ballista_points' },
    { off = 0x50, size = 4, name = 'fellow_points' },
    { off = 0x54, size = 2, name = 'chocobucks_sandoria_team' },
    { off = 0x56, size = 2, name = 'chocobucks_bastok_team' },
    { off = 0x58, size = 2, name = 'chocobucks_windurst_team' },
    { off = 0x5A, size = 2, name = 'daily_tally' },
    { off = 0x5C, size = 4, name = 'research_marks' },
    { off = 0x60, size = 1, name = 'wizened_tunnel_worms' },
    { off = 0x61, size = 1, name = 'wizened_morion_worms' },
    { off = 0x62, size = 1, name = 'wizened_phantom_worms' },
    { off = 0x64, size = 4, name = 'moblin_marbles' },
    { off = 0x68, size = 2, name = 'infamy' },
    { off = 0x6A, size = 2, name = 'prestige' },
    { off = 0x6C, size = 4, name = 'legion_points' },
    { off = 0x70, size = 4, name = 'sparks_of_eminence' },
    { off = 0x74, size = 4, name = 'shining_stars' },
    { off = 0x78, size = 4, name = 'imperial_standing' },
    { off = 0x7C, size = 4, name = 'assault_points_leujaoam' },
    { off = 0x80, size = 4, name = 'assault_points_mamool_ja' },
    { off = 0x84, size = 4, name = 'assault_points_lebros' },
    { off = 0x88, size = 4, name = 'assault_points_periqia' },
    { off = 0x8C, size = 4, name = 'assault_points_ilrusi' },
    { off = 0x90, size = 4, name = 'tokens' },
    { off = 0x94, size = 4, name = 'zeni' },
    { off = 0x98, size = 4, name = 'jettons' },
    { off = 0x9C, size = 4, name = 'therion_ichor' },
    { off = 0xA0, size = 4, name = 'allied_notes' },
    { off = 0xA4, size = 2, name = 'copper_aman_vouchers_stored' },
    { off = 0xA6, size = 2, name = 'login_points' },
    { off = 0xA8, size = 4, name = 'cruor' },
    { off = 0xAC, size = 4, name = 'resistance_credits' },
    { off = 0xB0, size = 4, name = 'dominion_notes' },
    { off = 0xB4, size = 1, name = 'echelon_battle_trophies_5th' },
    { off = 0xB5, size = 1, name = 'echelon_battle_trophies_4th' },
    { off = 0xB6, size = 1, name = 'echelon_battle_trophies_3rd' },
    { off = 0xB7, size = 1, name = 'echelon_battle_trophies_2nd' },
    { off = 0xB8, size = 1, name = 'echelon_battle_trophies_1st' },
    { off = 0xB9, size = 1, name = 'cave_conservation_points' },
    { off = 0xBA, size = 1, name = 'imperial_army_id_tags' },
    { off = 0xBB, size = 1, name = 'op_credits' },
    { off = 0xBC, size = 4, name = 'traverser_stones' },
    { off = 0xC0, size = 4, name = 'voidstones' },
    { off = 0xC4, size = 4, name = 'kupofrieds_corundums' },
    { off = 0xC8, size = 1, name = 'moblin_pheromone_sacks' },
    { off = 0xCA, size = 1, name = 'rems_tale_chapter_1_stored' },
    { off = 0xCB, size = 1, name = 'rems_tale_chapter_2_stored' },
    { off = 0xCC, size = 1, name = 'rems_tale_chapter_3_stored' },
    { off = 0xCD, size = 1, name = 'rems_tale_chapter_4_stored' },
    { off = 0xCE, size = 1, name = 'rems_tale_chapter_5_stored' },
    { off = 0xCF, size = 1, name = 'rems_tale_chapter_6_stored' },
    { off = 0xD0, size = 1, name = 'rems_tale_chapter_7_stored' },
    { off = 0xD1, size = 1, name = 'rems_tale_chapter_8_stored' },
    { off = 0xD2, size = 1, name = 'rems_tale_chapter_9_stored' },
    { off = 0xD3, size = 1, name = 'rems_tale_chapter_10_stored' },
    { off = 0xD4, size = 'bits', bits = 9, bit_offset = 0, name = 'bloodshed_plans_stored' },
    { off = 0xD4, size = 'bits', bits = 9, bit_offset = 9, name = 'umbrage_plans_stored' },
    { off = 0xD4, size = 'bits', bits = 9, bit_offset = 18, name = 'ritualistic_plans_stored' },
    { off = 0xD4, size = 'bits', bits = 9, bit_offset = 27, name = 'tutelary_plans_stored' },
    { off = 0xD4, size = 'bits', bits = 9, bit_offset = 36, name = 'primacy_plans_stored' },
    { off = 0xDC, size = 2, name = 'reclamation_marks' },
    { off = 0xE0, size = 4, name = 'unity_accolades' },
    { off = 0xE4, size = 2, name = 'fire_crystals_stored' },
    { off = 0xE6, size = 2, name = 'ice_crystals_stored' },
    { off = 0xE8, size = 2, name = 'wind_crystals_stored' },
    { off = 0xEA, size = 2, name = 'earth_crystals_stored' },
    { off = 0xEC, size = 2, name = 'lightning_crystals_stored' },
    { off = 0xEE, size = 2, name = 'water_crystals_stored' },
    { off = 0xF0, size = 2, name = 'light_crystals_stored' },
    { off = 0xF2, size = 2, name = 'dark_crystals_stored' },
    { off = 0xF4, size = 2, name = 'deeds' },
};

data.packet_113_display_names = T{
    'conquest_points_sandoria',
    'conquest_points_bastok',
    'conquest_points_windurst',
    'beastman_seals_stored',
    'kindred_seals_stored',
    'kindred_crests_stored',
    'high_kindred_crests_stored',
    'sacred_kindred_crests_stored',
    'ancient_beastcoins_stored',
    'valor_points',
    'scylds',
    'fire_crystals_stored',
    'ice_crystals_stored',
    'wind_crystals_stored',
    'earth_crystals_stored',
    'lightning_crystals_stored',
    'water_crystals_stored',
    'light_crystals_stored',
    'dark_crystals_stored',
    'guild_points_fishing',
    'guild_points_woodworking',
    'guild_points_smithing',
    'guild_points_goldsmithing',
    'guild_points_weaving',
    'guild_points_leathercraft',
    'guild_points_bonecraft',
    'guild_points_alchemy',
    'guild_points_cooking',
    'cinders',
    'synergy_fewell_fire',
    'synergy_fewell_ice',
    'synergy_fewell_wind',
    'synergy_fewell_earth',
    'synergy_fewell_lightning',
    'synergy_fewell_water',
    'synergy_fewell_light',
    'synergy_fewell_dark',
    'daily_tally',
    'ballista_points',
    'fellow_points',
    'chocobucks_sandoria_team',
    'chocobucks_bastok_team',
    'chocobucks_windurst_team',
    'research_marks',
    'wizened_tunnel_worms',
    'wizened_morion_worms',
    'wizened_phantom_worms',
    'moblin_pheromone_sacks',
    'moblin_marbles',
    'cave_conservation_points',
    'infamy',
    'prestige',
    'legion_points',
    'sparks_of_eminence',
    'deeds',
    'copper_aman_vouchers_stored',
    'reclamation_marks',
    'shining_stars',
    'imperial_standing',
    'assault_points_leujaoam',
    'assault_points_mamool_ja',
    'assault_points_lebros',
    'assault_points_periqia',
    'assault_points_ilrusi',
    'tokens',
    'imperial_army_id_tags',
    'zeni',
    'jettons',
    'therion_ichor',
    'bloodshed_plans_stored',
    'umbrage_plans_stored',
    'ritualistic_plans_stored',
    'tutelary_plans_stored',
    'primacy_plans_stored',
    'allied_notes',
    'op_credits',
    'cruor',
    'resistance_credits',
    'dominion_notes',
    'echelon_battle_trophies_5th',
    'echelon_battle_trophies_4th',
    'echelon_battle_trophies_3rd',
    'echelon_battle_trophies_2nd',
    'echelon_battle_trophies_1st',
    'traverser_stones',
    'voidstones',
    'kupofrieds_corundums',
    'unity_accolades',
    'rems_tale_chapter_1_stored',
    'rems_tale_chapter_2_stored',
    'rems_tale_chapter_3_stored',
    'rems_tale_chapter_4_stored',
    'rems_tale_chapter_5_stored',
    'rems_tale_chapter_6_stored',
    'rems_tale_chapter_7_stored',
    'rems_tale_chapter_8_stored',
    'rems_tale_chapter_9_stored',
    'rems_tale_chapter_10_stored',
    'login_points',
};

data.packet_118_fields = T{
    { off = 0x00, size = 4, name = 'bayld' },
    { off = 0x04, size = 2, name = 'kinetic_units' },
    { off = 0x06, size = 1, name = 'coalition_imprimaturs' },
    { off = 0x07, size = 1, name = 'mystical_canteens' },
    { off = 0x08, size = 4, name = 'obsidian_fragments' },
    { off = 0x0C, size = 2, name = 'lebondopt_wings_stored' },
    { off = 0x0E, size = 2, name = 'pulchridopt_wings_stored' },
    { off = 0x10, size = 4, name = 'mweya_plasm_corpuscles' },
    { off = 0x14, size = 1, name = 'ghastly_stones_stored' },
    { off = 0x15, size = 1, name = 'ghastly_stones_plus_1_stored' },
    { off = 0x16, size = 1, name = 'ghastly_stones_plus_2_stored' },
    { off = 0x17, size = 1, name = 'verdigris_stones_stored' },
    { off = 0x18, size = 1, name = 'verdigris_stones_plus_1_stored' },
    { off = 0x19, size = 1, name = 'verdigris_stones_plus_2_stored' },
    { off = 0x1A, size = 1, name = 'wailing_stones_stored' },
    { off = 0x1B, size = 1, name = 'wailing_stones_plus_1_stored' },
    { off = 0x1C, size = 1, name = 'wailing_stones_plus_2_stored' },
    { off = 0x1D, size = 1, name = 'snowslit_stones_stored' },
    { off = 0x1E, size = 1, name = 'snowslit_stones_plus_1_stored' },
    { off = 0x1F, size = 1, name = 'snowslit_stones_plus_2_stored' },
    { off = 0x20, size = 1, name = 'snowtip_stones_stored' },
    { off = 0x21, size = 1, name = 'snowtip_stones_plus_1_stored' },
    { off = 0x22, size = 1, name = 'snowtip_stones_plus_2_stored' },
    { off = 0x23, size = 1, name = 'snowdim_stones_stored' },
    { off = 0x24, size = 1, name = 'snowdim_stones_plus_1_stored' },
    { off = 0x25, size = 1, name = 'snowdim_stones_plus_2_stored' },
    { off = 0x26, size = 1, name = 'snoworb_stones_stored' },
    { off = 0x27, size = 1, name = 'snoworb_stones_plus_1_stored' },
    { off = 0x28, size = 1, name = 'snoworb_stones_plus_2_stored' },
    { off = 0x29, size = 1, name = 'leafslit_stones_stored' },
    { off = 0x2A, size = 1, name = 'leafslit_stones_plus_1_stored' },
    { off = 0x2B, size = 1, name = 'leafslit_stones_plus_2_stored' },
    { off = 0x2C, size = 1, name = 'leaftip_stones_stored' },
    { off = 0x2D, size = 1, name = 'leaftip_stones_plus_1_stored' },
    { off = 0x2E, size = 1, name = 'leaftip_stones_plus_2_stored' },
    { off = 0x2F, size = 1, name = 'leafdim_stones_stored' },
    { off = 0x30, size = 1, name = 'leafdim_stones_plus_1_stored' },
    { off = 0x31, size = 1, name = 'leafdim_stones_plus_2_stored' },
    { off = 0x32, size = 1, name = 'leaforb_stones_stored' },
    { off = 0x33, size = 1, name = 'leaforb_stones_plus_1_stored' },
    { off = 0x34, size = 1, name = 'leaforb_stones_plus_2_stored' },
    { off = 0x35, size = 1, name = 'duskslit_stones_stored' },
    { off = 0x36, size = 1, name = 'duskslit_stones_plus_1_stored' },
    { off = 0x37, size = 1, name = 'duskslit_stones_plus_2_stored' },
    { off = 0x38, size = 1, name = 'dusktip_stones_stored' },
    { off = 0x39, size = 1, name = 'dusktip_stones_plus_1_stored' },
    { off = 0x3A, size = 1, name = 'dusktip_stones_plus_2_stored' },
    { off = 0x3B, size = 1, name = 'duskdim_stones_stored' },
    { off = 0x3C, size = 1, name = 'duskdim_stones_plus_1_stored' },
    { off = 0x3D, size = 1, name = 'duskdim_stones_plus_2_stored' },
    { off = 0x3E, size = 1, name = 'duskorb_stones_stored' },
    { off = 0x3F, size = 1, name = 'duskorb_stones_plus_1_stored' },
    { off = 0x40, size = 1, name = 'duskorb_stones_plus_2_stored' },
    { off = 0x41, size = 1, name = 'pellucid_stones_stored' },
    { off = 0x42, size = 1, name = 'fern_stones_stored' },
    { off = 0x43, size = 1, name = 'taupe_stones_stored' },
    { off = 0x44, size = 2, name = 'mellidopt_wings_stored' },
    { off = 0x46, size = 2, name = 'escha_beads' },
    { off = 0x48, size = 4, name = 'escha_silt' },
    { off = 0x4C, size = 4, name = 'potpourri' },
    { off = 0x50, size = 4, name = 'hallmarks' },
    { off = 0x54, size = 4, name = 'total_hallmarks' },
    { off = 0x58, size = 4, name = 'badges_of_gallantry' },
    { off = 0x5C, size = 4, name = 'crafter_points' },
    { off = 0x60, size = 1, name = 'fire_crystals_set' },
    { off = 0x61, size = 1, name = 'ice_crystals_set' },
    { off = 0x62, size = 1, name = 'wind_crystals_set' },
    { off = 0x63, size = 1, name = 'earth_crystals_set' },
    { off = 0x64, size = 1, name = 'lightning_crystals_set' },
    { off = 0x65, size = 1, name = 'water_crystals_set' },
    { off = 0x66, size = 1, name = 'light_crystals_set' },
    { off = 0x67, size = 1, name = 'dark_crystals_set' },
    { off = 0x68, size = 1, name = 'mc_i_sr01s_set', label = 'MC-I-SR01s Set' },
    { off = 0x69, size = 1, name = 'mc_i_sr02s_set', label = 'MC-I-SR02s Set' },
    { off = 0x6A, size = 1, name = 'mc_i_sr03s_set', label = 'MC-I-SR03s Set' },
    { off = 0x6B, size = 1, name = 'liquefaction_spheres_set' },
    { off = 0x6C, size = 1, name = 'induration_spheres_set' },
    { off = 0x6D, size = 1, name = 'detonation_spheres_set' },
    { off = 0x6E, size = 1, name = 'scission_spheres_set' },
    { off = 0x6F, size = 1, name = 'impaction_spheres_set' },
    { off = 0x70, size = 1, name = 'reverberation_spheres_set' },
    { off = 0x71, size = 1, name = 'transfixion_spheres_set' },
    { off = 0x72, size = 1, name = 'compression_spheres_set' },
    { off = 0x73, size = 1, name = 'fusion_spheres_set' },
    { off = 0x74, size = 1, name = 'distortion_spheres_set' },
    { off = 0x75, size = 1, name = 'fragmentation_spheres_set' },
    { off = 0x76, size = 1, name = 'gravitation_spheres_set' },
    { off = 0x77, size = 1, name = 'light_spheres_set' },
    { off = 0x78, size = 1, name = 'darkness_spheres_set' },
    { off = 0x7C, size = 4, name = 'silver_aman_vouchers_stored' },
    { off = 0x80, size = 4, name = 'domain_points' },
    { off = 0x84, size = 4, name = 'domain_points_earned_today' },
    { off = 0x88, size = 4, name = 'mog_segments' },
    { off = 0x8C, size = 4, name = 'gallimaufry' },
    { off = 0x90, size = 2, name = 'is_accolades', label = 'Imperial Standing Accolades' },
    { off = 0x94, size = 4, name = 'temenos_units' },
    { off = 0x98, size = 4, name = 'apollyon_units' },
};

data.packet_118_display_names = T{
        'bayld',
        'coalition_imprimaturs',
        'kinetic_units',
        'obsidian_fragments',
        'lebondopt_wings_stored',
        'pulchridopt_wings_stored',
        'mellidopt_wings_stored',
        'ghastly_stones_stored',
        'ghastly_stones_plus_1_stored',
        'ghastly_stones_plus_2_stored',
        'verdigris_stones_stored',
        'verdigris_stones_plus_1_stored',
        'verdigris_stones_plus_2_stored',
        'wailing_stones_stored',
        'wailing_stones_plus_1_stored',
        'wailing_stones_plus_2_stored',
        'snowslit_stones_stored',
        'snowslit_stones_plus_1_stored',
        'snowslit_stones_plus_2_stored',
        'snowtip_stones_stored',
        'snowtip_stones_plus_1_stored',
        'snowtip_stones_plus_2_stored',
        'snowdim_stones_stored',
        'snowdim_stones_plus_1_stored',
        'snowdim_stones_plus_2_stored',
        'snoworb_stones_stored',
        'snoworb_stones_plus_1_stored',
        'snoworb_stones_plus_2_stored',
        'leafslit_stones_stored',
        'leafslit_stones_plus_1_stored',
        'leafslit_stones_plus_2_stored',
        'leaftip_stones_stored',
        'leaftip_stones_plus_1_stored',
        'leaftip_stones_plus_2_stored',
        'leafdim_stones_stored',
        'leafdim_stones_plus_1_stored',
        'leafdim_stones_plus_2_stored',
        'leaforb_stones_stored',
        'leaforb_stones_plus_1_stored',
        'leaforb_stones_plus_2_stored',
        'duskslit_stones_stored',
        'duskslit_stones_plus_1_stored',
        'duskslit_stones_plus_2_stored',
        'dusktip_stones_stored',
        'dusktip_stones_plus_1_stored',
        'dusktip_stones_plus_2_stored',
        'duskdim_stones_stored',
        'duskdim_stones_plus_1_stored',
        'duskdim_stones_plus_2_stored',
        'duskorb_stones_stored',
        'duskorb_stones_plus_1_stored',
        'duskorb_stones_plus_2_stored',
        'mweya_plasm_corpuscles',
        'escha_silt',
        'escha_beads',
        'pellucid_stones_stored',
        'fern_stones_stored',
        'taupe_stones_stored',
        'potpourri',
        'crafter_points',
        'fire_crystals_set',
        'ice_crystals_set',
        'wind_crystals_set',
        'earth_crystals_set',
        'lightning_crystals_set',
        'water_crystals_set',
        'light_crystals_set',
        'dark_crystals_set',
        'mc_i_sr01s_set',
        'mc_i_sr02s_set',
        'mc_i_sr03s_set',
        'liquefaction_spheres_set',
        'induration_spheres_set',
        'detonation_spheres_set',
        'scission_spheres_set',
        'impaction_spheres_set',
        'reverberation_spheres_set',
        'transfixion_spheres_set',
        'compression_spheres_set',
        'fusion_spheres_set',
        'distortion_spheres_set',
        'fragmentation_spheres_set',
        'gravitation_spheres_set',
        'light_spheres_set',
        'darkness_spheres_set',
        'hallmarks',
        'total_hallmarks',
        'badges_of_gallantry',
        'silver_aman_vouchers_stored',
        'mystical_canteens',
        'domain_points',
        'domain_points_earned_today',
        'mog_segments',
        'gallimaufry',
        'is_accolades',
        'temenos_units',
        'apollyon_units',
};

data.item_labels = {
        fire_crystals_stored = 'Fire Crystals Stored',
        ice_crystals_stored = 'Ice Crystals Stored',
        wind_crystals_stored = 'Wind Crystals Stored',
        earth_crystals_stored = 'Earth Crystals Stored',
        lightning_crystals_stored = 'Lightning Crystals Stored',
        water_crystals_stored = 'Water Crystals Stored',
        light_crystals_stored = 'Light Crystals Stored',
        dark_crystals_stored = 'Dark Crystals Stored',
    };

data.help_indices = {
        fire_crystals_stored = 281,
        ice_crystals_stored = 282,
        wind_crystals_stored = 283,
        earth_crystals_stored = 284,
        lightning_crystals_stored = 285,
        water_crystals_stored = 286,
        light_crystals_stored = 287,
        dark_crystals_stored = 288,
        copper_aman_vouchers_stored = 90,
        bloodshed_plans_stored = 91,
        umbrage_plans_stored = 92,
        ritualistic_plans_stored = 93,
        tutelary_plans_stored = 94,
        primacy_plans_stored = 95,
        rems_tale_chapter_1_stored = 250,
        rems_tale_chapter_2_stored = 251,
        rems_tale_chapter_3_stored = 252,
        rems_tale_chapter_4_stored = 253,
        rems_tale_chapter_5_stored = 254,
        rems_tale_chapter_6_stored = 255,
        rems_tale_chapter_7_stored = 256,
        rems_tale_chapter_8_stored = 257,
        rems_tale_chapter_9_stored = 258,
        rems_tale_chapter_10_stored = 259,
        login_points = 280,
        daily_tally = 89,
        hallmarks = 289,
        total_hallmarks = 290,
        badges_of_gallantry = 291,
        crafter_points = 293,
        deeds = 292,
        reclamation_marks = 260,
        imperial_standing = 46,
        bayld = 57,
        kinetic_units = 58,
        coalition_imprimaturs = 75,
        mystical_canteens = 320,
        obsidian_fragments = 59,
        lebondopt_wings_stored = 60,
        pulchridopt_wings_stored = 61,
        ghastly_stones_stored = 119,
        ghastly_stones_plus_1_stored = 120,
        ghastly_stones_plus_2_stored = 121,
        verdigris_stones_stored = 122,
        verdigris_stones_plus_1_stored = 123,
        verdigris_stones_plus_2_stored = 124,
        wailing_stones_stored = 125,
        wailing_stones_plus_1_stored = 126,
        wailing_stones_plus_2_stored = 127,
        snowslit_stones_stored = 128,
        snowslit_stones_plus_1_stored = 129,
        snowslit_stones_plus_2_stored = 130,
        snowtip_stones_stored = 131,
        snowtip_stones_plus_1_stored = 132,
        snowtip_stones_plus_2_stored = 133,
        snowdim_stones_stored = 134,
        snowdim_stones_plus_1_stored = 135,
        snowdim_stones_plus_2_stored = 136,
        snoworb_stones_stored = 137,
        snoworb_stones_plus_1_stored = 138,
        snoworb_stones_plus_2_stored = 139,
        leafslit_stones_stored = 140,
        leafslit_stones_plus_1_stored = 141,
        leafslit_stones_plus_2_stored = 142,
        leaftip_stones_stored = 143,
        leaftip_stones_plus_1_stored = 144,
        leaftip_stones_plus_2_stored = 145,
        leafdim_stones_stored = 146,
        leafdim_stones_plus_1_stored = 147,
        leafdim_stones_plus_2_stored = 148,
        leaforb_stones_stored = 149,
        leaforb_stones_plus_1_stored = 150,
        leaforb_stones_plus_2_stored = 151,
        duskslit_stones_stored = 152,
        duskslit_stones_plus_1_stored = 153,
        duskslit_stones_plus_2_stored = 154,
        dusktip_stones_stored = 155,
        dusktip_stones_plus_1_stored = 156,
        dusktip_stones_plus_2_stored = 157,
        duskdim_stones_stored = 158,
        duskdim_stones_plus_1_stored = 159,
        duskdim_stones_plus_2_stored = 160,
        duskorb_stones_stored = 161,
        duskorb_stones_plus_1_stored = 162,
        duskorb_stones_plus_2_stored = 163,
        pellucid_stones_stored = 261,
        fern_stones_stored = 262,
        taupe_stones_stored = 263,
        mellidopt_wings_stored = 203,
        escha_silt = 220,
        escha_beads = 221,
        potpourri = 264,
        fire_crystals_set = 294,
        ice_crystals_set = 295,
        wind_crystals_set = 296,
        earth_crystals_set = 297,
        lightning_crystals_set = 298,
        water_crystals_set = 299,
        light_crystals_set = 300,
        dark_crystals_set = 301,
        mc_i_sr01s_set = 302,
        mc_i_sr02s_set = 303,
        mc_i_sr03s_set = 304,
        liquefaction_spheres_set = 305,
        induration_spheres_set = 306,
        detonation_spheres_set = 307,
        scission_spheres_set = 308,
        impaction_spheres_set = 309,
        reverberation_spheres_set = 310,
        transfixion_spheres_set = 311,
        compression_spheres_set = 312,
        fusion_spheres_set = 313,
        distortion_spheres_set = 314,
        fragmentation_spheres_set = 315,
        gravitation_spheres_set = 316,
        light_spheres_set = 317,
        darkness_spheres_set = 318,
        silver_aman_vouchers_stored = 319,
        domain_points = 321,
        domain_points_earned_today = 322,
        gallimaufry = 366,
        mog_segments = 367,
        is_accolades = 373,
        temenos_units = 374,
        apollyon_units = 375,
    };

return data;

