local data = {};

-- Home Point destination indices from the client/community HomePoint map.
data.points = T{
    { index = 0, zone_label = "Southern San d'Oria", number = 1 },
    { index = 1, zone_label = "Southern San d'Oria", number = 2 },
    { index = 2, zone_label = "Southern San d'Oria", number = 3 },
    { index = 3, zone_label = "Northern San d'Oria", number = 1 },
    { index = 4, zone_label = "Northern San d'Oria", number = 2 },
    { index = 5, zone_label = "Northern San d'Oria", number = 3 },
    { index = 6, zone_label = "Port San d'Oria", number = 1 },
    { index = 7, zone_label = "Port San d'Oria", number = 2 },
    { index = 8, zone_label = "Port San d'Oria", number = 3 },
    { index = 9, zone_label = "Bastok Mines", number = 1 },
    { index = 10, zone_label = "Bastok Mines", number = 2 },
    { index = 11, zone_label = "Bastok Markets", number = 1 },
    { index = 12, zone_label = "Bastok Markets", number = 2 },
    { index = 13, zone_label = "Bastok Markets", number = 3 },
    { index = 14, zone_label = "Port Bastok", number = 1 },
    { index = 15, zone_label = "Port Bastok", number = 2 },
    { index = 16, zone_label = "Metalworks", number = 1 },
    { index = 17, zone_label = "Windurst Waters", number = 1 },
    { index = 18, zone_label = "Windurst Waters", number = 2 },
    { index = 19, zone_label = "Windurst Walls", number = 1 },
    { index = 20, zone_label = "Windurst Walls", number = 2 },
    { index = 21, zone_label = "Windurst Walls", number = 3 },
    { index = 22, zone_label = "Port Windurst", number = 1 },
    { index = 23, zone_label = "Port Windurst", number = 2 },
    { index = 24, zone_label = "Port Windurst", number = 3 },
    { index = 25, zone_label = "Windurst Woods", number = 1 },
    { index = 26, zone_label = "Windurst Woods", number = 2 },
    { index = 27, zone_label = "Windurst Woods", number = 3 },
    { index = 28, zone_label = "Windurst Woods", number = 4 },
    { index = 29, zone_label = "Ru'Lude Gardens", number = 1 },
    { index = 30, zone_label = "Ru'Lude Gardens", number = 2 },
    { index = 31, zone_label = "Ru'Lude Gardens", number = 3 },
    { index = 32, zone_label = "Upper Jeuno", number = 1 },
    { index = 33, zone_label = "Upper Jeuno", number = 2 },
    { index = 34, zone_label = "Upper Jeuno", number = 3 },
    { index = 35, zone_label = "Lower Jeuno", number = 1 },
    { index = 36, zone_label = "Lower Jeuno", number = 2 },
    { index = 37, zone_label = "Port Jeuno", number = 1 },
    { index = 38, zone_label = "Port Jeuno", number = 2 },
    { index = 39, zone_label = "Kazham", number = 1 },
    { index = 40, zone_label = "Mhaura", number = 1 },
    { index = 41, zone_label = "Norg", number = 1 },
    { index = 42, zone_label = "Rabao", number = 1 },
    { index = 43, zone_label = "Selbina", number = 1 },
    { index = 44, zone_label = "Western Adoulin", number = 1 },
    { index = 45, zone_label = "Eastern Adoulin", number = 1 },
    { index = 46, zone_label = "Ceizak Battlegrounds", number = 1 },
    { index = 47, zone_label = "Foret de Hennetiel", number = 1 },
    { index = 48, zone_label = "Morimar Basalt Fields", number = 1 },
    { index = 49, zone_label = "Yorcia Weald", number = 1 },
    { index = 50, zone_label = "Marjami Ravine", number = 1 },
    { index = 51, zone_label = "Kamihr Drifts", number = 1 },
    { index = 52, zone_label = "Yughott Grotto", number = 1 },
    { index = 53, zone_label = "Palborough Mines", number = 1 },
    { index = 54, zone_label = "Giddeus", number = 1 },
    { index = 55, zone_label = "Fei'Yin", number = 1 },
    { index = 56, zone_label = "Quicksand Caves", number = 1 },
    { index = 57, zone_label = "Den of Rancor", number = 1 },
    { index = 58, zone_label = "Castle Zvahl Keep", number = 1 },
    { index = 59, zone_label = "Ru'Aun Gardens", number = 1 },
    { index = 60, zone_label = "Ru'Aun Gardens", number = 2 },
    { index = 61, zone_label = "Ru'Aun Gardens", number = 3 },
    { index = 62, zone_label = "Ru'Aun Gardens", number = 4 },
    { index = 63, zone_label = "Ru'Aun Gardens", number = 5 },
    { index = 64, zone_label = "Tavnazian Safehold", number = 1 },
    { index = 65, zone_label = "Aht Urhgan Whitegate", number = 1 },
    { index = 66, zone_label = "Nashmau", number = 1 },
    { index = 67, zone_label = "Al Zahbi", number = 1 },
    { index = 68, zone_label = "Southern San d'Oria [S]", number = 1 },
    { index = 69, zone_label = "Bastok Markets [S]", number = 1 },
    { index = 70, zone_label = "Windurst Waters [S]", number = 1 },
    { index = 71, zone_label = "Upper Delkfutt's Tower", number = 1 },
    { index = 72, zone_label = "The Shrine of Ru'Avitau", number = 1 },
    { index = 73, zone_label = "Riverne - Site #B01", number = 1 },
    { index = 74, zone_label = "Bhaflau Thickets", number = 1 },
    { index = 75, zone_label = "Caedarva Mire", number = 1 },
    { index = 76, zone_label = "Uleguerand Range", number = 1 },
    { index = 77, zone_label = "Uleguerand Range", number = 2 },
    { index = 78, zone_label = "Uleguerand Range", number = 3 },
    { index = 79, zone_label = "Uleguerand Range", number = 4 },
    { index = 80, zone_label = "Uleguerand Range", number = 5 },
    { index = 81, zone_label = "Attohwa Chasm", number = 1 },
    { index = 82, zone_label = "Pso'Xja", number = 1 },
    { index = 83, zone_label = "Newton Movalpolos", number = 1 },
    { index = 84, zone_label = "Riverne - Site #A01", number = 1 },
    { index = 85, zone_label = "Al'Taieu", number = 1 },
    { index = 86, zone_label = "Al'Taieu", number = 2 },
    { index = 87, zone_label = "Al'Taieu", number = 3 },
    { index = 88, zone_label = "Grand Palace of Hu'Xzoi", number = 1 },
    { index = 89, zone_label = "The Garden of Ru'Hmet", number = 1 },
    { index = 90, zone_label = "Mount Zhayolm", number = 1 },
    { index = 91, zone_label = "Cape Teriggan", number = 1 },
    { index = 92, zone_label = "The Boyahda Tree", number = 1 },
    { index = 93, zone_label = "Den of Rancor", number = 2 },
    { index = 94, zone_label = "Fei'Yin", number = 2 },
    { index = 95, zone_label = "Ifrit's Cauldron", number = 1 },
    { index = 96, zone_label = "Quicksand Caves", number = 2 },
    { index = 97, zone_label = "Southern San d'Oria", number = 4 },
    { index = 98, zone_label = "Northern San d'Oria", number = 4 },
    { index = 99, zone_label = "Bastok Mines", number = 3 },
    { index = 100, zone_label = "Bastok Markets", number = 4 },
    { index = 101, zone_label = "Port Bastok", number = 3 },
    { index = 102, zone_label = "Metalworks", number = 2 },
    { index = 103, zone_label = "Windurst Waters", number = 3 },
    { index = 104, zone_label = "Norg", number = 2 },
    { index = 105, zone_label = "Rabao", number = 2 },
    { index = 106, zone_label = "Aht Urhgan Whitegate", number = 2 },
    { index = 107, zone_label = "Aht Urhgan Whitegate", number = 3 },
    { index = 108, zone_label = "Aht Urhgan Whitegate", number = 4 },
    { index = 109, zone_label = "Western Adoulin", number = 2 },
    { index = 110, zone_label = "Eastern Adoulin", number = 2 },
    { index = 111, zone_label = "Xarcabard [S]", number = 1 },
    { index = 112, zone_label = "Leafallia", number = 1 },
    { index = 113, zone_label = "Castle Zvahl Keep [S]", number = 1 },
    { index = 114, zone_label = "Qufim Island", number = 1 },
    { index = 115, zone_label = "Toraimarai Canal", number = 1 },
    { index = 116, zone_label = "Ra'Kaznar Inner Court", number = 1 },
    { index = 117, zone_label = "Misareaux Coast", number = 1 },
    { index = 118, zone_label = "Windurst Waters", number = 4 },
    { index = 119, zone_label = "Windurst Woods", number = 5 },
    { index = 120, zone_label = "Tavnazian Safehold", number = 2 },
    { index = 121, zone_label = "Tavnazian Safehold", number = 3 },
};

return data;
