-- THE PROMYVION TOPOLOGY A BLIND PLAYER WALKS ON MUST BE COMPLETE AND CLOSED.
--
-- The four Promyvions are floor-islands joined only by Memory Streams: a
-- receptacle kill opens one stream for 180 seconds, the chosen stream is
-- server-side random and UNKNOWABLE, returns are always open, and the exit is a
-- scripted teleport. A row missing from this file is a floor the runtime cannot
-- name, which for this project is the failure worse than a crash.
--
-- Data under test: data/ffxi-nav-promyvion-transitions.tsv, generated by
-- tools/generate_promyvion_navigation.py from the local LandSandBoat checkout
-- (scripts/globals/promyvion.lua receptacleInfoTable + each zone's trigger
-- registrations + npc_list/mob_spawn_points positions). This file asserts the
-- CONTRACT, not the generator: if the TSV is regenerated from a newer LSB and a
-- floor loses its way out, this goes red.
--
--   luajit tools/test_promyvion_navigation_data.lua
--
-- Exit code 1 on any failed claim.

local ROOT = os.getenv('ACCESSXI_ROOT') or 'C:/Users/buu42/AccessXI';
local TSV = ROOT .. '/data/ffxi-nav-promyvion-transitions.tsv';

local passed, failed = 0, 0;
local function claim(cond, what)
    if (cond) then passed = passed + 1; print('  ok   ' .. what);
    else failed = failed + 1; print('  FAIL ' .. what); end
end
local function trim(s) return (tostring(s or ''):gsub('^%s+', ''):gsub('%s+$', '')); end

local COLUMNS = {
    'record_id', 'zone', 'island_id', 'kind', 'group_id', 'name',
    'anchor_x', 'anchor_z', 'anchor_y', 'radius',
    'entity_server_id', 'paired_server_id',
    'destination_island', 'landing_x', 'landing_z', 'landing_y',
    'availability', 'window_seconds', 'source', 'confidence', 'note',
};

-- ---------------------------------------------------------------------------
-- Load. An absent or empty file is the RED state this test was born failing on.
-- ---------------------------------------------------------------------------
local handle = io.open(TSV, 'r');
claim(handle ~= nil, 'the generated TSV exists at ' .. TSV);
if (handle == nil) then
    print('');
    print(('promyvion navigation data: %d passed, %d failed'):format(passed, failed));
    os.exit(1);
end

local header, rows = nil, {};
for line in handle:lines() do
    if (line:sub(1, 1) ~= '#' and line:match('%S')) then
        local fields = {};
        for field in (line .. '\t'):gmatch('([^\t]*)\t') do fields[#fields + 1] = field; end
        if (header == nil) then
            header = fields;
        else
            local row = {};
            for i, name in ipairs(header) do row[name] = trim(fields[i]); end
            rows[#rows + 1] = row;
        end
    end
end
handle:close();

claim(header ~= nil and #header == #COLUMNS, 'the header carries all 21 columns');
for i, name in ipairs(COLUMNS) do
    claim(header ~= nil and trim(header[i]) == name,
        ('column %d is %s'):format(i, name));
end
claim(#rows > 0, ('rows parsed: %d'):format(#rows));

-- ---------------------------------------------------------------------------
-- Index by zone and island; reject duplicate record ids outright.
-- ---------------------------------------------------------------------------
local ZONES = { ['16'] = 'Holla', ['18'] = 'Dem', ['20'] = 'Mea', ['22'] = 'Vahzl' };
local by_zone, ids = {}, {};
local duplicate = nil;
for _, row in ipairs(rows) do
    local zone = row.zone;
    by_zone[zone] = by_zone[zone] or { islands = {}, forwards = {}, returns = {}, exits = {}, all = {} };
    table.insert(by_zone[zone].all, row);
    if (row.kind == 'island') then by_zone[zone].islands[row.island_id] = row;
    elseif (row.kind == 'forward') then table.insert(by_zone[zone].forwards, row);
    elseif (row.kind == 'return') then table.insert(by_zone[zone].returns, row);
    elseif (row.kind == 'exit') then table.insert(by_zone[zone].exits, row);
    end
    if (ids[row.record_id]) then duplicate = row.record_id; end
    ids[row.record_id] = true;
end
claim(duplicate == nil, 'record ids are unique' .. (duplicate and (', duplicate: ' .. duplicate) or ''));

for zone, label in pairs(ZONES) do
    claim(by_zone[zone] ~= nil, ('zone %s (%s) is present'):format(zone, label));
end

-- ---------------------------------------------------------------------------
-- Per-zone structural closure.
-- ---------------------------------------------------------------------------
for _, zone in ipairs({ '16', '18', '20', '22' }) do
    local z = by_zone[zone] or { islands = {}, forwards = {}, returns = {}, exits = {}, all = {} };
    local label = ZONES[zone];

    -- Every forward row is a receptacle/stream PAIR: the stream entity whose
    -- animation is the open evidence, and the receptacle whose death opens it.
    -- The ids are the exact ones receptacleInfoTable binds; a forward row
    -- missing either is a portal the runtime can neither watch nor explain.
    local paired = 0;
    for _, row in ipairs(z.forwards) do
        if (tonumber(row.entity_server_id) ~= nil and tonumber(row.paired_server_id) ~= nil
            and tonumber(row.entity_server_id) > 0 and tonumber(row.paired_server_id) > 0) then
            paired = paired + 1;
        end
    end
    claim(paired == #z.forwards,
        ('%s: every forward row has both a Stream and a Receptacle id (%d of %d)')
            :format(label, paired, #z.forwards));

    -- Every island can be LEFT: a forward or return edge starts on it, except
    -- none -- even the final floor has its always-open return.
    for island_id, island in pairs(z.islands) do
        local outgoing = 0;
        for _, row in ipairs(z.forwards) do
            if (row.island_id == island_id) then outgoing = outgoing + 1; end
        end
        for _, row in ipairs(z.returns) do
            if (row.island_id == island_id) then outgoing = outgoing + 1; end
        end
        for _, row in ipairs(z.exits) do
            if (row.island_id == island_id) then outgoing = outgoing + 1; end
        end
        claim(outgoing > 0,
            ('%s: island %s has a way off it (%d edges)'):format(label, island_id, outgoing));
    end

    -- Every destination an edge names is an island that exists. An exit names a
    -- zone instead, and must say so in the zone:<id> form.
    for _, row in ipairs(z.forwards) do
        claim(z.islands[row.destination_island] ~= nil,
            ('%s: forward %s lands on a real island (%s)')
                :format(label, row.record_id, row.destination_island));
    end
    for _, row in ipairs(z.returns) do
        claim(z.islands[row.destination_island] ~= nil,
            ('%s: return %s lands on a real island (%s)')
                :format(label, row.record_id, row.destination_island));
    end
    for _, row in ipairs(z.exits) do
        claim(row.destination_island:match('^zone:%d+$') ~= nil,
            ('%s: exit %s names its destination zone (%s)')
                :format(label, row.record_id, row.destination_island));
    end

    -- Availability is the load-bearing column. A forward stream is NEVER
    -- assumed open -- the chosen portal is server-side random and unknowable,
    -- so the only honest value is evidence-gated with the 180-second window
    -- LSB's openDoor(180) defines. Returns and the exit are always open.
    for _, row in ipairs(z.forwards) do
        claim(row.availability == 'stream-open-evidence' and row.window_seconds == '180',
            ('%s: forward %s is evidence-gated with a 180s window'):format(label, row.record_id));
    end
    for _, row in ipairs(z.returns) do
        claim(row.availability == 'always',
            ('%s: return %s is always available'):format(label, row.record_id));
    end
    for _, row in ipairs(z.exits) do
        claim(row.availability == 'always',
            ('%s: the exit is always available'):format(label));
    end

    -- Islands may leave entity ids blank; forwards may not (asserted above).
    for _, row in ipairs(z.all) do
        claim(row.source ~= '' and row.confidence ~= '',
            ('%s: %s carries provenance (%s) and confidence (%s)')
                :format(label, row.record_id, row.source, row.confidence));
    end
end

-- ---------------------------------------------------------------------------
-- The two zone-specific shapes the plan pins.
-- ---------------------------------------------------------------------------
local holla = by_zone['16'] or { islands = {}, forwards = {} };
local holla_islands = 0;
for _ in pairs(holla.islands) do holla_islands = holla_islands + 1; end
claim(holla_islands == 5,
    ('Holla has its five islands, got %d'):format(holla_islands));
claim(#holla.forwards == 11,
    ('Holla has its eleven forward candidates, got %d'):format(#holla.forwards));

local vahzl = by_zone['22'] or { islands = {} };
local vahzl_floors = 0;
for island_id in pairs(vahzl.islands) do
    if (island_id:match('^floor%-%d$')) then vahzl_floors = vahzl_floors + 1; end
end
claim(vahzl_floors == 5,
    ('Vahzl has its five floors, got %d'):format(vahzl_floors));

-- The branch returns: Holla, Dem and Mea floor 4 return to EITHER third-floor
-- island depending on a charvar the client cannot read, so the data must carry
-- one row per destination rather than pretending the answer is single.
for _, zone in ipairs({ '16', '18', '20' }) do
    local z = by_zone[zone] or { returns = {} };
    local branch = 0;
    for _, row in ipairs(z.returns) do
        if (row.island_id == 'floor-4') then branch = branch + 1; end
    end
    claim(branch == 2,
        ('%s: the floor-4 return carries both destinations, got %d'):format(ZONES[zone], branch));
end

print('');
print(('promyvion navigation data: %d passed, %d failed'):format(passed, failed));
os.exit(failed == 0 and 0 or 1);
